# Generated by Django 3.0.2 on 2020-01-24 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basurero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('horaInicio', models.CharField(max_length=5)),
                ('horaFin', models.CharField(max_length=5)),
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('calificacion', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='BasureroCalificado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeback', models.TextField()),
                ('fechaCalificado', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.FloatField()),
                ('basurero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocateTrash.Basurero')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LocateTrash.Usuario')),
            ],
        ),
    ]
