# Generated by Django 3.0.2 on 2020-01-24 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LocateTrash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basurero',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='basurero',
            name='horaFin',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='basurero',
            name='horaInicio',
            field=models.CharField(default='00:00', max_length=5),
        ),
        migrations.AlterField(
            model_name='basurerocalificado',
            name='calificacion',
            field=models.FloatField(default=0.0),
        ),
    ]
